# Generated by Django 5.0.6 on 2024-06-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=20)),
                ('rainfall_mm', models.FloatField()),
                ('rainfall_change_percentage', models.FloatField()),
                ('temperature_celsius', models.FloatField()),
                ('temperature_change_celsius', models.FloatField()),
            ],
        ),
    ]
